server:
  port: 8888

spring:
  config:
    import: optional:configserver:http://localhost:8888


  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Amit-Dhakal/config-server
          clone-on-start: true
          default-label: master





