server:
  port: 8082

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/moviedb"
    username: root
    password: root1
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  application:
    name: movie-cataloge-service
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka




